#!/bin/sh
# /lib/elogind/system-sleep/lock
# Lock before suspend integration with elogind

username=rasa
userhome=/home/$username
export XAUTHORITY="$userhome/.Xauthority"
export DISPLAY=":0.0"
case "${1}/${2}" in
    pre/suspend)
	su $username -c "/usr/local/bin/slock"& sleep 1;
        ;;
esac

