#!/usr/bin/env sh

# Description: cd to any dir in the z database using an fzf pane
#
# Shell: POSIX compliant
# Author: Nick Waywood

. "$(dirname "$0")"/.nnn-plugin-helper

fuzzy=fzf
datafile="/home/rasa/.local/share/z/.z"
sel=$(awk -F "|" '{print $1}' "$datafile" | "$fuzzy" | awk '{$1=$1};1')

printf "%s" "0c$sel" > "$NNN_PIPE"
