[colors.primary]
background = "#282a36"
foreground = "#ebdbb2"

[font]
size = 16

[font.normal]
family = "Hack Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[window]
decorations = "none"
opacity = 0.95
